#!/bin/bash

if docker --version &>/dev/null; then
    echo "Docker is already installed."
else
    echo "Installing docker ...."
    curl -s https://raw.githubusercontent.com/GAGAN028/CICD/refs/heads/main/Dockerfile | sudo bash
fi
echo "Create volumes for sonarqube to persist data"
docker volume create --name sonarqube-data
docker volume create --name sonarqube-logs 
docker volume create --name sonarqube-extensions

docker run -d -it --name sonarqube \
    -p 9000:9000 \
    -e SONAR_JDBC_USERNAME=admin \
    -e SONAR_JDBC_PASSWORD=admin \
    -v sonarqube_data:/opt/sonarqube/data \	
	-v sonarqube_extensions:/opt/sonarqube/extensions \
    -v sonarqube_logs:/opt/somarqube/logs \
	sonarqube
	
echo "SonarQube, a default user with Administer System permission is created automatically:"
echo "Login: admin. Password: admin"
